In [67]:
import numpy as np
import itertools

cube = (np.array(list(itertools.product([0, 1], repeat=3))) - 0.5)*2 # cube in world coordinates
cube_id = cube.copy()                                                    # cube with no translation or rotations 
rotation_matrix = np.array([[0.707, -0.707, 0], [0.707, 0.707, 0], [0, 0, 1]])
cube_rot = np.dot(cube, rotation_matrix)
cube = cube_rot + 5                                                      # cube in camera coordinates; t = 5, R = the above


# image of cube from (0,0,0)
f = 10
true_pts = np.array([[f*x/z, f*y/z] for x,y,z in cube])                  # cube, downsampled to 2D image plane; say this is the PICTURE

In [68]:
rotation_matrix

array([[ 0.707, -0.707,  0.   ],
       [ 0.707,  0.707,  0.   ],
       [ 0.   ,  0.   ,  1.   ]])

In [69]:
# FIND THE POSE GIVEN TRUE_PTS AND CUBE_ID

In [90]:
cube_id[0] # M_0
true_pts[0] # m_0

array([ 8.965, 12.5  ])

In [120]:
# vector_xy = (true_pts-true_pts[0])[1:]
vector_xy = np.array((true_pts[:,0]-true_pts[0][0], true_pts[:,1]-true_pts[0][1])).T[1:,:]
IJ = np.linalg.pinv(cube_id[1:] - cube_id[0]) @ vector_xy
ij = IJ/np.linalg.norm(IJ, axis=0)
R = np.array([ij[:,0], ij[:,1], np.cross(ij[:,0], ij[:,1])])
s = np.linalg.norm(IJ[:,0])
m0 = np.array([true_pts[0][0], true_pts[0][1], 1])
t = (m0-cube_id[0])/s
R, t

(array([[ 0.54011723,  0.54011723, -0.64540433],
        [-0.49996224,  0.49996224, -0.70716017],
        [-0.0592716 ,  0.70462719,  0.54007645]]),
 array([3.3219606 , 4.5003982 , 0.66672566]))